### ISSUE TITLE
如何在jest里集成macaca-report

### ISSUE THREAD

**Issue by jcheng-wish** [macacajs/macaca-reporter-jest#3]
例如通过jest测试小程序的自动化，
1:如何在test case的代码里添加语句增加截图功能；
2:运行test case的时候怎么生成报告。
可否在readme文件里写明如何使用，并且给个sample code,非常感谢。

**Comment by Jodeee** [comment]
你好，可以在jest.config.js文件中进行如下配置：
module.exports = {
  testEnvironment: 'node',
  reporters: ["default", ["macaca-reporter-jest", {}]],
  moduleDirectories: ["node_modules"]
};
在运行测试后即可生成报告，关于截图可直接使用你现有的框架能力来完成，不过目前报告中用例还无法和截图关联，这一点我们正在解决。

**Comment by jcheng-wish** [comment]
好的，感谢您的回复，目前生成了报告，请问报告中的用例和截图关联预期什么时候解决呢？有其他额外的已经解决该问题的测试框架可以使用吗？

**Comment by Jodeee** [comment]
可以使用 [macaca-reporter](https://github.com/macacajs/macaca-reporter) ，支持展示用例截图的
